"""`setup_path()` must also install a `renco-acp` launcher.

ACP hosts (Zed, JetBrains, Buzz Desktop) spawn the agent by resolving a command
name against the login-shell PATH. The `renco-acp` console script generated by
the packaging metadata lives inside the install's venv, which is not on that
PATH, so those hosts report Renco as not installed. `setup_path()` therefore
writes a `renco-acp` launcher next to the `renco` one.

These tests drive the real block out of `scripts/install.sh` rather than
asserting on a copy of it, so the shim cannot drift away from the test.
"""

import re
import stat
import subprocess
from pathlib import Path
from unittest.mock import patch

INSTALL_SH = Path(__file__).resolve().parent.parent / "scripts" / "install.sh"

ACP_BLOCK = re.compile(
    r'(    rm -f "\$command_link_dir/renco-acp".*?'
    r'log_success "Installed renco-acp launcher[^\n]*\n)',
    re.S,
)


def _extract_acp_shim_block() -> str:
    match = ACP_BLOCK.search(INSTALL_SH.read_text(encoding="utf-8"))
    assert match, (
        "could not locate the renco-acp launcher block in scripts/install.sh — "
        "if it was renamed, update this test with it"
    )
    return match.group(1)


def _run_block(tmp_path: Path, use_venv: str) -> Path:
    """Execute the extracted block with the env vars setup_path() sets."""
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    renco_bin = tmp_path / "venv" / "bin" / "python"
    renco_bin.parent.mkdir(parents=True)
    renco_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    entrypoint = tmp_path / "renco"
    entrypoint.write_text("#!/bin/sh\n", encoding="utf-8")

    script = (
        "set -e\n"
        f"RENCO_BIN={renco_bin}\n"
        f"RENCO_ENTRYPOINT={entrypoint}\n"
        f"command_link_dir={command_link_dir}\n"
        f"command_link_display_dir={command_link_dir}\n"
        f"USE_VENV={use_venv}\n"
        "log_success(){ :; }\n" + _extract_acp_shim_block()
    )
    result = subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        cwd=tmp_path,
    )
    assert result.returncode == 0, (
        f"acp shim block failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    return command_link_dir / "renco-acp"


def test_venv_install_writes_executable_acp_launcher(tmp_path):
    shim = _run_block(tmp_path, "true")
    assert shim.is_file()
    assert shim.stat().st_mode & stat.S_IXUSR, "launcher must be user-executable"

    text = shim.read_text(encoding="utf-8")
    assert "unset PYTHONPATH" in text
    assert "unset PYTHONHOME" in text
    # The launcher must dispatch to the ACP subcommand, otherwise the host gets
    # an interactive CLI on stdio and the handshake never completes.
    assert re.search(r'exec .*\bacp\b', text), text


def test_non_venv_install_writes_acp_launcher(tmp_path):
    shim = _run_block(tmp_path, "false")
    text = shim.read_text(encoding="utf-8")
    assert re.search(r'exec .*\bacp\b', text), text


def test_acp_launcher_does_not_follow_a_symlink_into_the_venv(tmp_path):
    """Guards the #21454 failure mode for the new launcher.

    An older install could leave `renco-acp` as a symlink to the venv console
    script. Without the `rm -f`, `cat >` follows it and overwrites that script
    with a shim that then execs itself.
    """
    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    console_script = tmp_path / "venv" / "bin" / "renco-acp"
    console_script.parent.mkdir(parents=True)
    marker = "#!/usr/bin/env python\n# real console script\n"
    console_script.write_text(marker, encoding="utf-8")

    shim_path = command_link_dir / "renco-acp"
    shim_path.symlink_to(console_script)
    assert shim_path.is_symlink()

    renco_bin = tmp_path / "venv" / "bin" / "python"
    renco_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    entrypoint = tmp_path / "renco"
    entrypoint.write_text("#!/bin/sh\n", encoding="utf-8")

    script = (
        "set -e\n"
        f"RENCO_BIN={renco_bin}\n"
        f"RENCO_ENTRYPOINT={entrypoint}\n"
        f"command_link_dir={command_link_dir}\n"
        f"command_link_display_dir={command_link_dir}\n"
        "USE_VENV=true\n"
        "log_success(){ :; }\n" + _extract_acp_shim_block()
    )
    result = subprocess.run(
        ["bash", "-c", script], capture_output=True, text=True, cwd=tmp_path
    )
    assert result.returncode == 0, result.stderr

    assert console_script.read_text(encoding="utf-8") == marker, (
        "venv/bin/renco-acp was overwritten — symlink-stomp regression (#21454)"
    )
    assert not shim_path.is_symlink(), (
        "command_link_dir/renco-acp must be replaced with a regular file"
    )


# ---------------------------------------------------------------------------
# renco-agent launcher regression (#74819)
# ---------------------------------------------------------------------------

RENCO_AGENT_BLOCK = re.compile(
    r'(rm -f "\$command_link_dir/renco-agent".*?'
    r'log_success "Installed renco-agent launcher[^\n]*\n)',
    re.S,
)


def _extract_renco_agent_shim_block() -> str:
    match = RENCO_AGENT_BLOCK.search(INSTALL_SH.read_text(encoding="utf-8"))
    assert match, (
        "could not locate the renco-agent launcher block in scripts/install.sh — "
        "if it was renamed, update this test with it"
    )
    return match.group(1)


def _run_renco_agent_block(tmp_path: Path, use_venv: str) -> Path | None:
    """Execute the extracted renco-agent block with the env vars setup_path() sets."""
    if use_venv == "false":
        # --no-venv: renco-agent is NOT installed by this block (handled
        # elsewhere), so there's nothing to test here.
        return None

    command_link_dir = tmp_path / "local_bin"
    command_link_dir.mkdir()
    renco_bin = tmp_path / "venv" / "bin" / "python"
    renco_bin.parent.mkdir(parents=True)
    renco_bin.write_text("#!/bin/sh\n", encoding="utf-8")
    install_dir = tmp_path / "install"
    install_dir.mkdir()

    script = (
        "set -e\n"
        f"RENCO_BIN={renco_bin}\n"
        f"INSTALL_DIR={install_dir}\n"
        f"command_link_dir={command_link_dir}\n"
        f"command_link_display_dir={command_link_dir}\n"
        f"USE_VENV={use_venv}\n"
        "log_success(){ :; }\n" + _extract_renco_agent_shim_block()
    )
    result = subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        cwd=tmp_path,
    )
    assert result.returncode == 0, (
        f"renco-agent shim block failed:\nstdout={result.stdout}\nstderr={result.stderr}"
    )
    return command_link_dir / "renco-agent"


def test_venv_install_writes_executable_renco_agent_launcher(tmp_path):
    """venv install must write a user-executable renco-agent launcher."""
    shim = _run_renco_agent_block(tmp_path, "true")
    assert shim is not None
    assert shim.is_file()
    assert shim.stat().st_mode & stat.S_IXUSR, "launcher must be user-executable"

    text = shim.read_text(encoding="utf-8")
    assert "unset PYTHONPATH" in text
    assert "unset PYTHONHOME" in text
    assert "run_agent.py" in text, "renco-agent must dispatch to run_agent.py"


def test_renco_agent_launcher_cleanup_on_uninstall(tmp_path):
    """uninstall.remove_wrapper_script() must remove renco-agent alongside
    renco and renco-acp."""
    from renco_cli.uninstall import remove_wrapper_script

    # Simulate a renco-agent wrapper in the user-local location
    local_shim = tmp_path / ".local" / "bin" / "renco-agent"
    local_shim.parent.mkdir(parents=True)
    local_shim.write_text("#!/usr/bin/env bash\nexec renco-agent\n", encoding="utf-8")

    with patch.object(Path, "home", return_value=tmp_path):
        removed = remove_wrapper_script()

    assert local_shim in removed, "local renco-agent wrapper must be removed"
